### ISSUE TITLE
Incorrect output when longest string is the empty string

### ISSUE THREAD

**Issue by smammy** [jonschlinkert/longest#4]
Steps to replicate:

```
> var longest = require('longest');
> longest([""]);
```

Expected result:
`longest([""])` returns `""`.

Actual result:
`longest([""])` returns `undefined`.

**Comment by stevenvachon** [comment]
@jonschlinkert ?

**Comment by stevenvachon** [comment]
@jonschlinkert @smammy this can likely be closed.

**Comment by jonschlinkert** [comment]
@stevenvachon thanks! 

I believe this was resolved, I'm going to close but please feel free to reopen or create a new issue if you're still having problems.
